name: Base Reusable Build & Package Lib

# Reusing github actions workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows
on:
  workflow_call:
    inputs:
      lib_module:
        required: true
        type: string
      nx_configuration:
        required: true
        type: string
      node_auth_token:
        required: true
        type: string
    secrets:
      node_auth_token:
        required: true

env:
  # Required to integrate private organizational github packages
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-lib:
    name: Build and Publish
    runs-on: ubuntu-latest
    # outputs:
    #   tag: '${{ env.TAG }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com/
          scope: '@vipin-sharma-wiser'

      - name: Install NX
        uses: nrwl/nx-set-shas@v2

      - name: Cache Deps
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ inputs.lib_module }}-${{ inputs.nx_configuration }}-build-lib-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Format
      #   run: yarn nx format:check ${{ inputs.ui_module }}

      # - name: Module Lint
      #   run: yarn nx lint ${{ inputs.ui_module }}

      - name: Build
        run: yarn nx build ${{ inputs.lib_module }} --configuration=${{ inputs.nx_configuration }} --skip-nx-cache

      # - uses: ferluisxd/create-npmrc@3
      #   with:
      #     org_name: vipin-sharma-wiser
      #     auth_token: ${{ secrets.GITHUB_TOKEN }}
      - name: print .npmrc
        run: cat /home/runner/work/_temp/.npmrc

      - name: printenv
        run: printenv

      - name: Ensure access
        run: npm whoami --registry https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy npmrc file to build path
        run: cp /home/runner/work/_temp/.npmrc dist/libs/${{ inputs.lib_module }}

      - name: Navigate to build path
        run: cd dist/libs/${{ inputs.lib_module }}

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}